<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <title>Random Pets</title>
</head>

<body>

<?php
$getDog = file_get_contents('https://dog.ceo/api/breeds/image/random');
$dog = json_decode($getDog, true);

$getCat = file_get_contents('https://api.thecatapi.com/v1/images/search?limit=10');
$cat = json_decode($getCat, true)
?>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2 class="animate__animated animate__backInLeft">Random Dog</h2>
            <img src="<?php echo $dog['message'] ?>" class="img-fluid" alt="random dog">
        </div>
        <div class="col-md-6">
            <h2 class="animate__animated animate__backInRight">Random Cat</h2>
            <img src="<?php echo $cat[1]['url'] ?>" class="img-fluid" alt="random cat">
        </div>
    </div>
</div>



</body>
</html>